version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-ui:
    image: rediscommander/redis-commander:latest # Or another Redis UI like RedisInsight
    container_name: redis-ui
    environment:
      - REDIS_HOSTS=local:redis-db:6379
    ports:
      - "8081:8081"

volumes:
  redis-data:
